import {Router} from "express";
import {initiateSearchController} from "./search";
import { initiateInitController } from "./init";
import { initiateConfirmController } from "./confirm";
import { initiateStatusController } from "./status";
import { initiateUpdateController } from "./update";
import { initiateCancelController } from "./cancel";
export const initiateRouter = Router();
initiateRouter.post("/search", initiateSearchController);
initiateRouter.post("/init", initiateInitController);
initiateRouter.post("/confirm", initiateConfirmController);
initiateRouter.post("/status", initiateStatusController);
initiateRouter.post("/update", initiateUpdateController);
initiateRouter.post("/cancel", initiateCancelController);