version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
      - "${SSL_PORT}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      # - NGINX_PORT=${NGINX_PORT}
      # - USE_SSL=${USE_SSL}
      # - SSL_PORT=${SSL_PORT}
      - SSL_CERT_PATH=${SSL_CERT_PATH:-.}
    volumes:
      - ./nginx-${ENVIRONMENT}.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_CERT_PATH:-.}:/etc/nginx/certs:ro
    # command: ["sh", "-c", "nginx -g 'daemon off;'"]
    restart: always
    networks:
      - ondc
networks:
  ondc: