export const SERVICES_DOMAINS = {
	B2B: "b2b",
	SERVICES: "ONDC:SRV11",
	AGRI_SERVICES: "ONDC:SRV14",
	HEALTHCARE_SERVICES: "ONDC:SRV13",
	AGRI_EQUIPMENT: "ONDC:SRV17",
	BID_ACTION_SERVICES: "ONDC:SRV18",
	SUBSCRIPTION_PRINT_MEDIA: "ONDC:MEC10",
	SUBSCRIPTION_AUDIO_VIDEO: "ONDC:MEC11",
	AGRI_INPUT: "ONDC:AGR10",
	AGRI_OUTPUT: "ONDC:AGRI11"
};

export const ONEST_DOMAINS = {
	ONEST10: "ONDC:ONEST10",
	ONEST11: "ONDC:ONEST11",
	ONEST12: "ONDC:ONEST12",
	ONEST13: "ONDC:ONEST13"
}

export const ORDER_STATUS = {
	IN_PROGRESS: "In-progress",
	CREATED: "Created",
	ACTIVE: "Active",
	ACCEPTED: "Accepted",
	CANCELLED: "Cancelled",
	COMPLETED: "Completed",
};

export const FULFILLMENT_LABELS = {
	CONFIRMED: "confirmed",
	SELECTED: "selected",
	REJECTED: "rejected",
};

export const FULFILLMENT_STATES = {
	PENDING: "PENDING",
	APPLICATION_IN_PROGRESS: "APPLICATION_IN_PROGRESS",
  APPLICATION_FILLED: "APPLICATION_FILLED",
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  ASSESSMENT_IN_PROGRESS: "ASSESSMENT_IN_PROGRESS",
  OFFER_EXTENDED: "OFFER_EXTENDED",
  OFFER_REJECTED: "OFFER_REJECTED",
	CANCELLED: "CANCELLED",
	COMPLETED: "COMPLETED",
};

export const PAYMENT_STATUS = {
	PAID: "PAID",
	NON_PAID: "NOT-PAID",
};

export const PAYMENT_TYPE = {
	PRE_FULFILLMENT: "PRE-FULFILLMENT",
	ON_FULFILLMENT: "ON-FULFILLMENT",
	POST_FULFILLMENT: "POST-FULFILLMENT",
};
